### ISSUE TITLE
s3tk scan --object-level-logging GetEventSelectors trail name

### ISSUE THREAD

**Issue by JRodriguez556** [ankane/s3tk#18]
Got this error when running s3tk scan --object-level-logging :

`An error occurred (TrailNotFoundException) when calling the GetEventSelectors operation: Unknown trail: arn:aws:cloudtrail:us-west-2:xxxxxx:trail/yyyyyyy for the user: xxxxxxxxx`

~~I Think GetEventSelectors is expecting the short trail name of _yyyyyyy_ rather than the full ARN.~~

Edit: Looks like this issue was caused by the cloudtrail being in a different region than the default region set via aws configure. The above cloudtrail exists in us-east-1.

Edit: Typo's/Formatting

**Comment by ankane** [comment]
Hey @JRodriguez556, I'm not sure how to reproduce. It is passing the short name: https://github.com/ankane/s3tk/blob/e942aca2505a275b07cf1a58fd6759989d056a25/s3tk/__init__.py#L395

**Comment by JRodriguez556** [comment]
Looks like my default region was set to us-west-2 and the cloudtrail region is us-east-1. I changed my default region in `aws configure` to us-east-1 and recieved the following output when I reran s3tk scan --object-level-logging: 
 
```
$BUCKET_NAME
  ✔ ACL not open to public
  ✔ Policy not open to public
  ✔ Public access blocked
  ✘ Logging disabled
  ✘ Versioning disabled
  ✔ Default encryption enabled
Traceback (most recent call last):
  File "/usr/local/bin/s3tk", line 7, in <module>
    s3tk.cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s3tk/__init__.py", line 457, in scan
    checks.append(perform(ObjectLoggingCheck(bucket, event_selectors=event_selectors)))
  File "/usr/local/lib/python2.7/dist-packages/s3tk/__init__.py", line 80, in perform
    puts(colored.green('✔ ' + check.name + ' ' + check.pass_message))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by ankane** [comment]
Fixed the region and Python 2 issue. Python 2 won't be supported in the next release since it's EOL, but the command should work for now.

**Comment by ankane** [comment]
Currently, it only checks trails from your default region, meaning it can miss trails from other regions. We'd need to check every region for trails to make this fully correct (since trails in any region can be multi-region), but I don't plan to put any more time into this for now.
