### ISSUE TITLE
JSON Policy Issue for Encryption

### ISSUE THREAD

**Issue by burgerjeffrey** [ankane/s3tk#3]
When we try to apply the JSON IAM policy for s3tk, two s3 permissions come back as unrecognized actions: GetEncryptionConfiguration & PutEncryptionConfiguration.
They show as valid on this web page, so not sure why they are not recognized.  http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html#using-with-s3-actions-related-to-bucket-subresources

**Comment by ankane** [comment]
Hey @burgerjeffrey, thanks for reporting 👍  Both permissions work with my account fwiw. Maybe there is an issue somewhere else in the policy.

**Comment by ankane** [comment]
Cleaning up stale issues (no response)
