### ISSUE TITLE
grepable output?

### ISSUE THREAD

**Issue by craighurley** [ankane/s3tk#7]
While colours are pretty, I can't grep them.  Is there an option, or will there be an option to produce an output that's easier to parse for errors on a large set of buckets?

**Comment by ankane** [comment]
Hey @craighurley, the colors should only show up for interactive sessions. If you pipe it to grep or write it to a file, there should be no colors. Let me know if you're seeing something different.

**Comment by craighurley** [comment]
Sorry, I should have added more detail.  I would be nice if there were an indication of pass/fail in the outputted text.  While colours are pretty, they are of no use to me or grep.

**Comment by ankane** [comment]
Ah, I see. We could probably add `✔` and `✘` to each row.

**Comment by craighurley** [comment]
That would work.  The downside to using those particular characters or similar is that they are not easily typed in a terminal.  Old school simple usually works best.
